---
title: "Demographics in England by UK birth status"
author: "Sam Abbott"
date: "22/09/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages} 
library(tbinenglanddataclean)
library(tidyverse)
library(knitr)
library(ggridges)
library(viridis)
```

```{r clean-lfs-data, eval = FALSE}
## see tbinenglanddataclean for raw data sources
clean_labour_force_survey(data_path = "tb_data/LFS", years = 2000:2016, return = FALSE, save = TRUE, verbose = FALSE )
clean_demographics_uk(data_path = "tb_data/UK_demographics", demo_2000 = "UK_2000_age.csv", demo_2001_2015 = "UK_2001_2015_age.csv", countries = c("E"), return = FALSE, save = TRUE)
```

```{r load-data, message = FALSE}
 ## Load and clean england demographic data by UK birth status - tbinenglanddataclean
england_demographics <- combine_ons_with_lfs(data_path = "tb_data/tbinenglanddataclean",
  ons_name = "E_demo_2000_2015.rds",
  lfs_name = "formatted_LFS_2000_2016.rds", countries = "England",
  return = TRUE, save = FALSE, verbose = FALSE) %>% 
  select(Age, Year, Population, CoB) %>% 
  filter(CoB %in% c("UK born", "Non-UK born")) %>% 
  droplevels
```

```{r summmarise}
 ## look at demographics
summary(england_demographics)
```

```{r filter-plot-save}
##Filter for those below 90
england_demographics <- england_demographics %>% 
  ungroup %>% 
  filter(!(Age %in% c("90+", "90"))) %>% 
  mutate(age = Age %>% 
           as.character %>% 
           as.numeric) %>% 
  select(-Age) %>% 
  rename(year = Year)

## Add age grouping used in analysis and summarise with proportions
england_demographics <- england_demographics %>% 
  mutate(age_group = cut(age, c(0, seq(5, 70, 5), 90),
                           labels = c(paste(seq(0, 65, 5),
                                          seq(4, 69, 5),
                                          sep = "-"), "70-89"),
                         right = FALSE,
                         ordered_result = TRUE)
                               ) %>% 
  group_by(year, age_group, CoB) %>% 
  summarise(population = sum(Population)) %>%
  group_by(year, CoB) %>% 
  mutate(proportion_age_by_year = population / sum(population)) %>% 
  ungroup

  ##summary of new data
  summary(england_demographics)
  
  ## Check currently estimated proportions
  england_demographics %>% 
    group_by(year, CoB) %>% 
    summarise(proportion_age_by_year = sum(proportion_age_by_year)) %>% 
    spread(CoB, proportion_age_by_year) %>% 
    kable
  
  #' Add demographics to the package
  devtools::use_data(england_demographics, overwrite = TRUE)

  #' Add as raw csv
  write_csv(england_demographics, "../data-raw/data-proc/england_demographics.csv")
```

```{r plot-uk-demographics, dpi = 330, fig.height = 7, fig.width = 7}
england_demographics %>% 
  filter(CoB %in% "UK born") %>% 
  filter((year %% 4) == 0 ) %>% 
  mutate(Year = factor(year, ordered = TRUE)) %>% 
  ggplot(aes(x = age_group, y = proportion_age_by_year, group = Year, fill = Year)) +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_viridis(discrete = TRUE) +
  geom_col(alpha = 0.8, position = "dodge") +
  theme_minimal() + 
  theme(legend.position = "bottom") +
  labs(y = "Proportion of the population (%)",
       x = "Age (5 year age groups from 0 to 69 and then 70-89)")

ggsave("figure/england_demographics.png", dpi = 330)
```
