---
title: "Disease Model Parameters"
output:   
    html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(knitr)
library(idmodelr)
```

```{r make table}
disease_params_table <- tibble(
  Parameter = "$C_{\\text{eff}}$",
  Description = "The assumed effective number of contacts per infectious TB case.",
  Distribution = "$\\mathcal{N}(1, 1)$ truncated to be greater than 0.",
  Units = "-",
  Type = "Vynnycky et al.",
  Source = "[@Vynnycky1999]",
  Method = "Estimated using a dynamic model of TB transmission in England which found an effective contact rate of 1 in 1990. A conservative interval has then been applied.",
  Setting = "England",
  Fitted = "Yes",
  URL = "-"
) %>%
  add_row(
      Parameter = "$C^{\\text{hist}}_{\\text{eff}}$",
  Description = "The assumed historic effective number of contacts per infectious TB case.",
  Distribution = "$\\mathcal{U}(C_{\\text{eff}}, 20)$",
  Units = "-",
  Source = "[@Vynnycky1999]",
  Type = "Vynnycky et al.",
  Method = "Estimated using a dynamic model of TB transmission in England which found an effective contact rate of 1 in 1990 and 20 in 1901. A conservative interval has been chosen to represent the parameter uncertainty. It has been assumed that the historic contact rate is bounded below by the current contact rate.",
  Setting = "England",
  Fitted = "Yes",
  URL = "-"
  ) %>% 
    add_row(
      Parameter = "$C^{\\text{half-life}}_{\\text{eff}}$",
  Description = "It is assumed that the historic effective contact rate decays from 1935 to 1980 with a half-life of C^{\\text{half-life}}_{\\text{eff}}.",
  Distribution = "$\\mathcal{N}(5, 5)$ truncated to be greater than 0.",
  Units = "-",
  Source = "",
  Type = "Assumption",
  Method = "The prior distribution is informed by historic TB notifications.",
  Setting = "England",
  Fitted = "Yes",
  URL = "-"
  ) %>% 
   add_row(
      Parameter = "$\\beta_{\\text{young-adult}}$",
  Description = "This parameter modifies the effective contact rate in scenarios when the transmission probability is modified for young adults (15-24).",
  Distribution = "$\\mathcal{U}(0, 10)$",
  Units = "-",
  Source = "Assumption",
  Type = "Assumption",
  Method = "An uninformative prior has been used bounded above to restrict the transmission probability in young adults to be no greater than 10 times that in other age-groups.",
  Setting = "England",
  Fitted = "Yes",
  URL = "-"
  ) %>% 
    add_row(
    Parameter = "$\\Upsilon$",
    Description = "The age-specific proportion of cases that have pulmonary TB",
    Distribution = "$\\Upsilon_{0-14,15-59,60-89} = \\mathcal{N}(0.629, 0.00101)$, $\\mathcal{N}(0.706, 0.00411)$, $\\mathcal{N}(0.750, 0.00569)$",
    Units = "Proportion",
    Source = "ETS",
    Type = "Derived from data",
    Method = "Estimated using the age-specific proportion of cases that had pulmonary TB in the ETS.",
    Setting = "England",
    Fitted = "No",
    URL = "-"
  ) %>% 
  add_row(
    Parameter = "$\\rho$",
    Description = "The age-specific proportion of pulmonary TB cases that are smear positive",
    Distribution = "$\\rho_{0-14,15-59,60-89} = \\mathcal{N}(0.302, 0.0189)$, $\\mathcal{N}(0.652, 0.00518)$, $\\mathcal{N}(0.536, 0.00845)$",
    Units = "Proportion",
    Source = "ETS",
    Type = "Derived from data",
    Method = "Estimated using the age-specific proportion of pulmonary TB cases that were smear postive in the ETS.",
    Setting = "England",
    Fitted = "No",
    URL = "-"
  ) %>%
add_row(
  Parameter = "$C$",
  Description = "Matrix of contact rates between each age group",
  Distribution = "-",
  Units = "Non-unique yearly contacts.",
  Source = "[@Mossong2008]",
  Type = "Mossong et al.",
  Method = "For each parameter sample a contact matrix was bootstrapped from the POLYMOD survey data, standardised using the UK born population in 2005, and then averaged to provided a symmetric contact matrix.",
  Setting = "United Kingdom",
  Fitted = "No",
  URL = "https://doi.org/10.1371/journal.pmed.0050074"
) %>%
add_row(
  Parameter = "$\\iota(t)$",
  Description = "The age-specific number of non-UK born pulmonary TB cases in England each year",
  Distribution = "-",
  Units = "Cases",
  Source = "ETS",
  Type = "Derived from data",
  Method = "The number of pulmonary non-UK born cases for each year were extracted from the ETS and grouped by age.",
  Setting = "England",
  Fitted = "No",
  URL = "-"
) %>%
add_row(
  Parameter = "$\\iota_{\\text{scale}}$",
  Description = "Scaling parameter for the importation of non-UK born cases between 1960 and 2000.",
  Distribution = "$\\mathcal{N}(0, 200)$",
  Units = "-",
  Source = "-",
  Type = "Assumption",
  Method = "This largely uninformative prior range was chosen so that non-UK born scaling can vary between approximately linear to approximately constant.",
  Setting = "England",
  Fitted = "Yes",
  URL = "-"
) %>%
  add_row(
    Parameter = "$M$",
    Description = "The proportion of mixing between the UK born and non-UK born population.",
    Distribution = "$\\mathcal{N}(1, 1)$ truncated to be greater than 0",
    Units = "Proportion",
    Source = "Assumption",
    Type = "Assumption",
    Method = "Any degree of mixing is allowed as there is little data on which to base this estimate. Mixing greater than 1 is allowed as this is used to represent non-UK born cases being in some way more infectious than non-UK born cases.",
    Setting = "-",
    Fitted = "Yes",
    URL = "-"
  ) %>% 
     add_row(
      Parameter = "$M_{\\text{young-adult}}$",
  Description = "This parameter modifies the non-UK born mixing rate in scenarios when $M$ is modified for young adults (15-24).",
  Distribution = "$\\mathcal{U}(0, 10)$",
  Units = "-",
  Source = "Assumption",
  Type = "Assumption",
  Method = "An uninformative prior has been used bounded above to restrict non-UK born mixing in young adults to be no greater than 10 times that in other age-groups.",
  Setting = "England",
  Fitted = "Yes",
  URL = "-"
  ) %>%
  add_row(
    Parameter = "$\\chi$",
    Description = "Age-specific protection from infection with TB due to BCG vaccination",
    Distribution = paste0("$\\chi^v_{i} = \\mathcal{N}(",
                          estimate_norm_dist_from_ci(0.08, 0.29)$mean, "$, $", 
                          signif(estimate_norm_dist_from_ci(0.08, 0.29)$sd, 3),  ")$, where $i$ is the age group vaccinated."),
    Units = "Proportion",
    Source = "[@Roy2014]",
    Type = "Roy et al.",
    Method = "A meta-analysis of the protection from infection due to BCG vaccinatiion in children. It has been assumed that there is no reduction in protection in UK born adults.",
    Setting = "Global",
    Fitted = "No",
    URL = "-"
  ) %>%
  add_row(
    Parameter = "$\\epsilon_H$",
    Description = "The age-specific rate of transition to active disease during high risk latent period.",
    Distribution = "$\\epsilon_H^{0-4,5-14,15-89} = \\mathcal{N}(0.00695, 0.00130)$, $\\mathcal{N}(0.0028, 0.000561)$, $\\mathcal{N}(0.000335, 0.0000893)$",
    Units = "$days^{-1}$",
    Source = "[@Ragonnet2017]",
    Type = "Ragonnet et al.",
    Method = "From fitting a similar model to contact data in Australia, and Holland. Distribution derived by the assumption of a normal distribution based on 95\\% credible intervals.",
    Setting = "Low incidence",
    Fitted = "No",
    URL = "https://doi.org/10.1016/j.epidem.2017.06.002"
  ) %>%
  add_row(
    Parameter = "$\\kappa$",
    Description = "The reciprocal of the age-specific average high risk latent period.",
    Distribution = "$\\kappa^{0-4,5-14,15-89} = \\mathcal{N}(0.0133, 0.00242)$, $\\mathcal{N}(0.0120, 0.00207)$, $\\mathcal{N}(0.00725, 0.00191)$",
    Units = "$days^{-1}$",
    Source = "[@Ragonnet2017]",
    Type = "Ragonnet et al.",
    Method = "From fitting a similar model to contact data in Australia, and Holland. Distribution derived by the assumption of a normal distribution based on 95\\% credible intervals." ,
    Setting = "Low incidence",
    Fitted = "No",
    URL = "https://doi.org/10.1016/j.epidem.2017.06.002"
  ) %>%
  add_row(
    Parameter = "$\\epsilon_L$",
    Description = "The reciprocal of the age-specific average low risk latent period.",
    Distribution = "$\\epsilon_L^{0-4,5-14,15-89} = \\mathcal{N}(8.00e^{-6}, 4.08e^{-6})$, $\\mathcal{N}(9.84e^{-6}, 4.67e^{-6})$, $\\mathcal{N}(5.95e^{-6}, 2.07e^{-6})$",
    Units = "$days^{-1}$",
    Source = "[@Ragonnet2017]",
    Type = "Ragonnet et al.",
    Method = "From fitting a similar model to contact data in Australia, and Holland. Distribution derived by the assumption of a normal distribution based on 95\\% credible intervals.",
    Setting = "Low incidence",
    Fitted = "No",
    URL = "https://doi.org/10.1016/j.epidem.2017.06.002"
  ) %>% 
    add_row(
    Parameter = "$\\epsilon^{\\text{older-adult}}_L$",
    Description = "This parameter modifies the activation rate of low risk latent cases who are 70+ and reduces the activaton rate for other adults so that the mean activation rate is $\\epsilon_L^{15-89}$",
    Distribution = "$\\mathcal{N}(2, 0.5)$ truncated to be at least 1.",
    Units = "-",
    Source = "[@HorsburghJr:2010bm]",
    Type = "Horsburgh, Jr. et al.",
    Method = "Evidence suggests that activation risk increases when individuals enter old age. A largely uninformative prior has been used centred around an increase in risk of double the average rate.",
    Setting = "Low incidence",
    Fitted = "No",
    URL = "https://doi.org/10.1164/rccm.200909-1355OC"
  ) %>%
  add_row(
    Parameter = "$\\alpha_i^T$",
    Description = "The BCG vaccine effectiveness at preventing the development of active TB disease in a TB free population",
    Distribution = "$\\alpha^T_{i,i+5,i+10,i+15,i+20,i+25} = 1 - e^{\\alpha^{\\text{ln}(T)}_{i,i+5,i+10,i+15,i+20,i+25}}$, where $\\alpha^{\\text{ln}(T)}_{i,i+5,i+10,i+15,i+20,i+25} = \\mathcal{N}(-1.86, 0.22)$, $\\mathcal{N}(-1.19, 0.24)$, $\\mathcal{N}(-0.84, 0.22)$, $\\mathcal{N}(-0.84, 0.2)$, $\\mathcal{N}(-0.28, 0.19)$, $\\mathcal{N}(-0.23, 0.29))$ and $i$ is the age group vaccinated",
    Units = "Proportion",
    Source = "[@Hart1972; @Mangtani2017] ",
    Type = "Hart et al. and Mangtani et al.",
    Method = "Poisson regression used to calculate Risk Ratios from literature values. A distribution is then found using the log normal approximation. Effectiveness estimates are caculated using 1 minus the exponentiated log normal distribution.",
    Setting = "England",
    Fitted = "No",
    URL = "-"
  ) %>%
  add_row(
    Parameter = "$\\delta$",
    Description = "Reduction in susceptibilty to infection for low risk latent cases.",
    Distribution = paste0("$\\mathcal{N}(",
                          estimate_norm_dist_from_ci(0.7, 0.86)$mean, "$, $", 
                          signif(estimate_norm_dist_from_ci(0.7, 0.86)$sd, 3), ")$"),
    Units = "Proportion",
    Source = "@Andrews2012",
    Type = "Andrews et al.",
    Method = "A review of prospective cohort studies of persons exposed to individuals with infectious tuberculosis that was published prior to the widespread treatment of latent tuberculosis.",
    Setting = "Global",
    Fitted = "No",
    URL = "-"
  ) %>%
  add_row(
    Parameter = "$\\nu^{P, E}$",
    Description = "The reciprocal of the average infectious period",
    Distribution = "$\\nu^P_{(0-14,15-89)} = \\mathcal{N}(0.181, 0.310)^{-1}$, $\\mathcal{N}(0.328, 0.447)^{-1}$, $\\nu^E_{(0-14, 15-89)} = \\mathcal{N}(0.306, 0.602	)^{-1}$, $\\mathcal{N}(0.480, 0.866)^{-1}$",
    Units = "$years^{-1}$",
    Source = "ETS",
    Type = "Derived from data",
    Method = "Estimated based on the time from initial symptoms to starting treatment",
    Setting = "England",
    Fitted = "No",
    URL = "-"
  ) %>% 
  add_row(
    Parameter = "$\\phi$",
    Description = "The reciprocal of the time to succesful treatment completion",
    Distribution = "$\\phi_{0-14,15-69,70-89} = \\mathcal{N}(0.606,0.237)^{-1}$, $\\mathcal{N}(0.645, 0.290)^{-1}$, $\\mathcal{N}(0.616, 0.265)^{-1}$ and truncated to be greater than 4 months",
    Units = "$years^{-1}$",
    Source = "ETS",
    Type = "Derived from data",
    Method = "Estimated based on the time from starting treatment to treatment completion.",
    Setting = "England",
    Fitted = "No",
    URL = "-"
  ) %>%
    add_row(
    Parameter = "$\\mu$",
    Description = "Rate of age-specific pulmonary/extra-pulmonary TB TB mortality",
    Distribution = "$\\mu_{0-14,15-59,60-89} = \\mathcal{N}(0.0039, 0.018)$, $\\mathcal{N}(0.0226, 0.00787)$, $\\mathcal{N}(0.117, 0.0165)$ truncated to be greater than 0.",
    Units = "$years^{-1}$",
    Source = "ETS",
    Type = "Derived from data",
    Method = "Estimated based on outcomes at 12 months where cause of death was known, including all-cause deaths in the denominator.",
    Setting = "England",
    Fitted = "No",
    URL = "-"
  ) %>% 
    add_row(
    Parameter = "$\\zeta$",
    Description = "Rate of loss to follow up",
    Distribution = "$\\zeta_{0-14,15-59,60-89} = \\mathcal{N}(0.00976, 0.0179)$, $\\mathcal{N}(0.0304, 0.00764)$, $\\mathcal{N}(0.00614, 0.0159)$, truncated to be greater than 0.",
    Units = "$years^{-1}$",
    Source = "ETS",
    Type = "Derived from data",
    Method = "Estimated based on outcomes at 12 months for TB cases",
    Setting = "England",
    Fitted = "No",
    URL = "-"
  )
```

```{r show-table, results = "asis"}
kable(disease_params_table, escape = FALSE, booktabs = TRUE)
```


```{r add-table-to-package}
## Add to package
usethis::use_data(disease_params_table, overwrite = TRUE)

##Add as raw csv
write_csv(disease_params_table, "data-proc/disease_params_table.csv")
```
