---
title: "Measurement Model Parameters"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(knitr)
```

```{r make table}
measurement_params_table <- tibble(
  Parameter = "$E_{\\text{syst}}$",
  Description = "Systematic reporting error of incident TB cases",
  Distribution = "$\\mathcal{N}(0.9, 0.05)$ truncated to be greater than 0.8 and lower than 1.",
  Units = "Proportion",
  Source = "Assumption",
  Type = "Assumption",
  Method = "Assumption is that underreporting of TB cases is more likely that exact, or over reporting.",
  Setting = "England",
  Fitted = "Yes",
  URL = "-"
) %>%
  add_row(
    Parameter = "$E_{\\text{noise}}$",
    Description = "Magnitude of reporting noise for incidence TB cases.",
    Distribution = "$\\mathcal{U}(0, 0.05)$.",

    Units = "Proportion",
    Source = "Assumption",
    Type = "Assumption",
    Method = "It is likely that reporting accuracy varies each year. An upper bound of 5% is used as this means that approximately 95% of observations will be within 20% of each other.",
    Setting = "England",
    Fitted = "Yes",
    URL = "-"
  )
```


```{r show-table}
kable(measurement_params_table, escape = FALSE, booktabs = TRUE)
```


```{r add-table-to-package}
## Add to package
usethis::use_data(measurement_params_table, overwrite = TRUE)

##Add as raw csv
write_csv(measurement_params_table, "data-proc/measurement_params_table.csv")
```
