---
title: "Time Varying Mortality Rates in England"
author: "Sam Abbott"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include = FALSE} 
library(tbinenglanddataclean)
library(tidyverse)
library(viridis)
```

```{r load-data, message = TRUE}
 ## Load and clean births in england data
 mortality_rates <- clean_and_munge_england_life_expectancy(life_tables_path = "tb_data/UK_demographics/england_life_tables.xls",
  sheets = paste0(seq(2013, 1980, -1), "-", seq(2015, 1982, -1)),
  return = TRUE, save = FALSE, verbose = TRUE)
```

```{r summmarise}
 ## look at births
 summary(mortality_rates)
```

```{r filter-plot-save}
## Summarise by year and age group as not modelling gender
mortality_rates <- mortality_rates %>% 
  filter(age < 90) %>% 
  group_by(mid_year, age) %>% 
  summarise(mortality_rate = mean(mortality_rate)) %>% 
  ungroup
  
## Add age grouping used in analysis
mortality_rates <- mortality_rates %>% 
  mutate(age_group = cut(age, c(0, seq(5, 70, 5), 90),
                           labels = c(paste(seq(0, 65, 5),
                                          seq(4, 69, 5),
                                          sep = "-"), "70-89"),
                           right = FALSE,
                           ordered_result = TRUE)) %>% 
  group_by(mid_year, age_group) %>% 
  summarise(mortality_rate = mean(mortality_rate)) %>% 
  na.omit

## Estimate future mortality rates
simulated_years <- tibble(mid_year = c(1931:1980, 2015:2100), data = "projected")

mortality_rates <- mortality_rates %>% 
  group_by(age_group) %>% 
  mutate(data = "observed") %>% 
  nest() %>% 
  mutate(model = map(data, ~ nls(mortality_rate ~ exp(a + b * mid_year), 
                                 start = list(a = 0, b = 0), data = .)),
         aug_data = map2(data, model, ~ 
                           bind_rows(.x,
                                     mutate(simulated_years, 
                                            mortality_rate = predict(.y,
                                                                      simulated_years) %>% 
                                              unlist))
         )
  ) %>% 
  unnest(aug_data) %>% 
  ungroup

## clean and estimate expected lifespan
mortality_rates <- mortality_rates %>% 
  rename(year = mid_year) %>% 
  mutate(exp_life_span = 1 / mortality_rate) %>% 
  arrange(year)
```

```{r graph-mort, dpi = 330, fig.height = 7, fig.width = 7}
## Graph data
mortality_rates %>% 
  ungroup %>% 
  rename(Data = data) %>% 
  ggplot(aes(x = year, y = exp_life_span, colour = Data)) +
  geom_point(size = 1, alpha = 0.9) +
  geom_line(aes(group = age_group), size = 0.9, alpha = 0.8) +
  facet_wrap(~age_group, scales = "free_y") +
  theme_minimal() +
  scale_color_viridis(discrete = TRUE, end = 0.7) +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90)) +
  labs(x = "Year", 
       y = "Expected lifespan at current risk (3 year rolling average)")

ggsave("figure/mortality.png", dpi = 330)
```

```{r summarise-save}
  ##summary of new data
  summary(mortality_rates)
  
  #' Add incidence data to the package
  devtools::use_data(mortality_rates, overwrite = TRUE)

  #' Add as raw csv
  write_csv(mortality_rates, "data-proc/mortality_rates.csv")
```
