---
title: "Model Sources"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(knitr)
```

```{r make table}
sources_table <- tibble(
  `Study Type` = "-",
  Setting = "England",
  Year = "2000-2015",
  Description = "The Enhanced Tuberculosis Surveillance System (ETS) is a robust national data collection system that collects demographic and microbiological data on all notified cases in England.",
  Source = "ETS",
  URL = "-"
) %>% 
  add_row(
  `Study Type` = "-",
  Setting = "England",
  Year = "-",
  Description = "The Office for National Statistics (ONS) compiles demographic, health, enconomic, and social data for the United Kingdom",
  Source = "ONS",
  URL = "-"
  ) %>% 
  add_row(
  `Study Type` = "Dynamic modelling study",
  Setting = "England",
  Year = "Up to 1990",
  Description = "Used a dynamic model of tuberculosis, robustly parameterised to the available evidence and including realistic population demographis to estimate the effective contact rate of TB over time until the 1990's in the UK born white male population.",
  Source = "[@Vynnycky1999]",
  URL = "-"
  )  %>% 
  add_row(
  `Study Type` = "Contact survey",
  Setting = "Europe - including the United Kingdom",
  Year = "2005",
  Description = "Conducted contact surveys, based on a contact diary, in multiple European countries. Contacts were stratified by age and type of contact. In the United Kingdom over a thousand people were surveyed.",
  Source = "[@Mossong2008]",
  URL = "-"
  ) %>% 
  add_row(
  `Study Type` = "Systematic review and meta-analysis",
  Setting = "Global",
  Year = "Up to 2014",
  Description = "A meta-analysis; conducted with the aim of determining whether BCG vaccination protects against Mycobacterium tuberculosis infection as assessed by interferon $\\gamma$ release assays (IGRA) in children. Estimated both protection from initial latent infection and active TB disease.",
  Source = "[@Roy2014]",
  URL = "-"
  ) %>% 
  add_row(
  `Study Type` = "Systematic review",
  Setting = "Global",
  Year = "Up to 2017",
  Description = "Aimed to determine which dynamic TB model structure best captured the observed activation dynamics of TB. Identified 6 different commonly used model structures and compared them by fitting to activation data from the Netherlands and Australia.",
  Source = "[@Ragonnet2017]",
  URL = "https://doi.org/10.1016/j.epidem.2017.06.002"
  ) %>% 
  add_row(
  `Study Type` = "Clinical trial",
  Setting = "England",
  Year = "1950-1965",
  Description = "Investigated the effectiveness of the BCG vaccine at preventing TB disease when given at what as then school-leaving age. Followed the cohort over 15 years and estimated the effectiveness of the BCG vaccien in 2.5 year intervals from vaccination.",
  Source = "[@Hart1972]",
  URL = ""
  ) %>% 
 add_row(
  `Study Type` = "Population based case-control study",
  Setting = "England",
  Year = "2002-2014",
  Description = "Recruited UK-born White subjects with TB and randomly sampled White community controls. Cox regression was used to adjusted for known confounders and the effectiveness of the BCG vaccine was estimated from 10 years after vaccination until 30 years after vaccinaton.",
  Source = "[@Mangtani2017]",
  URL = ""
  ) %>%
  add_row(
  `Study Type` = "Systematic review and meta-analysis",
  Setting = "Global",
  Year = "Up to 2012",
  Description = "Reviewed prospective cohort studies of persons exposed to individuals with infectious TB. Only included studies that were published before the widespread treatment of latent TB. Aimed to estimate the reduction in re-infection for latent TB cases.",
  Source = "[@Andrews2012]",
  URL = ""
   ) %>% 
  add_row(
  `Study Type` = "-",
  Setting = "England",
  Year = "-",
  Description = "Where data, or literature, sources were not available assumed values were used based on expert opinion",
  Source = "Assumption",
  URL = "-"
  )
```


```{r show-table}
kable(sources_table, format = "markdown")
```


```{r add-table-to-package}
## Add to package
devtools::use_data(sources_table, overwrite = TRUE)

##Add as raw csv
write_csv(sources_table, "data-proc/sources_table.csv")
```
