verbose <- TRUE
model <- "BaseLineModel"
test_fit <- TRUE
# Load packages -----------------------------------------------------------

library(tidyverse)
library(rbi)
library(rbi.helpers)


# Load the model ----------------------------------------------------------

if (is.character(model)) {
  model_file <- file.path(getwd(), "inst/bi", paste0(model, ".bi"))
  
  tb_model_raw <- bi_model(model_file)
}else{
  tb_model_raw <- model
}



# Generate data from the model --------------------------------------------

tb_data <- bi_generate_dataset(tb_model_raw, end_time = 100 * 12, noutputs = 100, seed = 1234)

if (verbose) {
  message("Summary of generated model")
  print(tb_data)
}


tb_data_df <- bi_read(tb_data)

if (verbose) {
  message("Variables in the generated data")
  print(names(tb_data_df))
}


# Plot incidence generated by the model -----------------------------------

if (verbose) {
  message("Plot generated number of cases detected each year based on priors:")
  tb_data_df$YearlyCases %>% 
    ggplot(aes(x = time, y = value)) +
    geom_point(size = 1.2) +
    geom_line(size = 1.1, alpha = 0.6) +
    theme_minimal() +
    labs(x = "Months",
         y = "Yearly notified cases")
}


# Load the model ----------------------------------------------------------

if (verbose) {
  message("Load the model as a compiled libbi object")
}

tb_model <- libbi(tb_model_raw)

if (verbose) {
  message("Sample priors")
}

tb_model <- sample(tb_model, target="prior", nsamples=1000, end_time=100*12, noutputs=100)

if (verbose) {
  message("Summary of prior sampling")
  print(tb_model)
  message("Load priors")
}
priors <- bi_read(tb_model)

if (verbose) {
  message("Structure of priors")
  str(priors)
}

if (test_fit) {
  message("Testing fitting using PMCMC")
  
  tb_model <- tb_model %>% 
    sample(target="posterior", nparticles=16, obs=tb_data, sample_obs=TRUE, nsamples=100, verbose = TRUE)
  
}
