---
title: "Model Report"
author: "Sam Abbott"
date: "`r Sys.Date()`"
output: html_document
vignette: >
  %\VignetteIndexEntry{Model Report}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include=FALSE}
model_dir <- "results/model-run-2018-09-05_13:28:10"

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, 
                      message = TRUE, cache = FALSE,
                      fig.path = file.path(model_dir, "plots"),
                      cache.path = file.path(model_dir, "report-cache"),
                      fig.align = 'center',
                      fig.length = 8, fig.width = 8)
```

- Load packages required for analysis

```{r, packages, include = FALSE}
library(tidyverse)
library(rbi.helpers)
library(prettypublisher)
library(ModelTBBCGEngland)
```


- Load the fitted model and prior draws.

```{r}
model <- ModelTBBCGEngland::read_libbi(file.path(model_dir, "libbi", "posterior"))
priors <- readRDS(file.path(model_dir, "data", "prior-params.rds"))
```

- Evaluate Posterior Traces

```{r prior-traces, fig.width = 16, fig.height = 16}
plot_param(model, scales = "free", plot_type = "trace") + theme(legend.position = "none")
```
- Plot overview of prior and posterior densities

```{r prior-overview, fig.height = 16, fig.width = 16}
plot_param(model, prior_params = priors, scales = "free")
```

- Table of priors and posteriors 


```{r prior-overview, fig.height = 16, fig.width = 16}
param_sum <- plot_param(model, prior_params = priors, plot_data = FALSE) %>% 
  group_by(Distribution, parameter, length) %>% 
  summarise(median = median(value), 
            lll = quantile(value, 0.025), 
            hhh = quantile(value, 0.975)) %>% 
  mutate(value = pretty_ci(median, lll, hhh, sep = ", ")) %>%
  group_by(Distribution, parameter) %>% 
  mutate(Parameter = case_when(max(length) > 1 ~ paste(parameter, 1:n(), sep = "-"),
                               TRUE ~ as.character(parameter))
         ) %>% 
  ungroup %>% 
  select(Distribution, Parameter, value) %>% 
  spread(key = "Distribution", value = "value") %>% 
  select(Parameter, Prior, Posterior)

knitr::kable(param_sum)
```

- Plot an overview of states 

```{r overview-states, fig.height = 16, fig.width = 16}
plot_state(model, summarise = TRUE)
```

- Plot an overview of states zoomed into 1990 onwards

- Plot an overview of states 

```{r overview-states-1990, fig.height = 16, fig.width = 16}
plot_state(model, summarise = TRUE, start_time = 59)
```

- Plot fitted states

```{r overview-states-1990-obs}
plot_state(model, states = c("YearlyHistPInc", "YearlyInc"), summarise = TRUE, start_time = 59)
```

- Plot age dsitributed cases

```{r overview-states-1990-age}
plot_state(model, states = c("YearlyAgeInc"), start_time = 59)
```
