#' Test Model
#'
#' @description A function to test the models in development through the full fitting pipeline based on synthetic data.
#' @param model A character string containing the model name. Alternatively a model loaded via `rbi::bi_model` may be passed.
#' @param gen_data Logical, defaults to /code{TRUE}. Should data be synthesised using the model and priors.
#' @param run_time Numeric, the number of years to run the model fitting and simulation for, defaults to 74 (i.e from 1931 until 2005).
#' @param plot_input_data Logical, defaults to \code{TRUE}. Should input data be plotted
#' @param sample_priors Logical, defaults to \code{FALSE}. Should the model priors be sampled.
#' @param nsamples Numeric, the number of samples to take from the priors. Defaults to 1000.
#' @param nparticles Numeric, the initial number of particles to use in the particle filters. 
#' @param nthreads Numeric, defaults to 4. The number of parallel jobs to run. The most efficient option is likely to be to match the 
#' number of cores available.
#' @param adapt_particles Logical, defaults to \code{FALSE}. Should the number of particles be adapted.
#' @param adapt_proposal  Logical, defaults to \code{TRUE}. Should the proposal be adjusted to improve the acceptance rate.
#' @param min_acc Numeric, defaults to 0.05. The minimum target acceptance rate.
#' @param max_acc Numeric, defaults to 0.4. The maximum target acceptance rate.
#' @param fit Logical, defaults to \code{TRUE}. Should the model be fitted with 1000 samples extracted.
#' @param save_output Logical, defaults to \code{FALSE}. Should the model results be saved as a test dataset.
#' @param verbose Logical, defaults to \code{TRUE}. Should progress messages and output be printed.
#' @param libbi_verbose Logical, defaults to \code{FALSE}. Should \code{libbi} produce verbose progress and warnings messages.
#' @param browse Logical, defaults to \code{FALSE}. Should the function be run in debug mode using \code{browser}.
#'
#' @return A LibBi model object based on the inputed test model.
#' @export
#'
#' @import rbi
#' @import rbi.helpers
#' @import ggplot2
#' @importFrom stats runif time
#' @importFrom utils str
#' @importFrom graphics plot
#' @examples
#' 
#' 
test_model <- function(model= "BaseLineModel", gen_data = TRUE, run_time = 74, plot_input_data = TRUE,
                       sample_priors = TRUE, nsamples = 1000, nparticles = 1, adapt_particles = FALSE,
                       adapt_proposal = FALSE, min_acc = 0.05, max_acc = 0.4, fit = FALSE, save_output = FALSE, 
                       nthreads = 4, verbose = TRUE, libbi_verbose = FALSE, browse = FALSE) {
  
  
  # Load the model ----------------------------------------------------------
  
  if (is.character(model)) {
    model_file <- system.file(package="ModelTBBCGEngland", paste0("bi/", model, ".bi"))
    
    tb_model_raw <- bi_model(model_file)
  }else{
    tb_model_raw <- model
  }
  
  
  # Allow for interactive debugging -----------------------------------------
  
  if (browse) {
    browser() 
  }
  
  # Generate data from the model --------------------------------------------
  if (gen_data) {
    
    if (verbose) {
      message("Generating data from model")
    }
    
    tb_data <- bi_generate_dataset(tb_model_raw, end_time = run_time * 12, 
                                   noutputs = 100, seed = 1234, verbose = libbi_verbose)
    
    if (verbose) {
      message("Summary of generated model data")
      print(tb_data)
    }
    
    
    tb_data_df <- bi_read(tb_data)
    
    if (verbose) {
      message("Variables in the generated data")
      print(names(tb_data_df))
    }
    
  }
  
  
  # Plot incidence generated by the model -----------------------------------
  if (plot_input_data) {
    
    time <- NULL; value <- NULL;
    
    message("Plot generated number of cases detected each year based on priors:")
    p_cases <- tb_data_df$YearlyCases %>% 
      ggplot(aes(x = time, y = value)) +
      geom_point(size = 1.2) +
      geom_line(size = 1.1, alpha = 0.6) +
      theme_minimal() +
      labs(x = "Months",
           y = "Yearly notified cases")
    
    print(p_cases)
    
  }

  
  # Load the model ----------------------------------------------------------
  
  if (verbose) {
    message("Load the model as a compiled libbi object")
  }
  
  tb_model <- libbi(tb_model_raw)
  
  
  # Sample from priors ------------------------------------------------------
if (sample_priors) {
  if (verbose) {
    message("Sample priors")
  }
  
  tb_model <- sample(tb_model, target="prior", nsamples = nsamples, end_time=run_time*12, 
                     noutputs=run_time, nparticles = nparticles, nthreads = nthreads, verbose = libbi_verbose)
  
  if (verbose) {
    message("Summary of prior sampling")
    print(tb_model)
    message("Load priors")
  }
  
  priors <- bi_read(tb_model)
  
  if (verbose) {
    message("Structure of priors")
    str(priors)
    
    message("Plot priors")
    print(plot(tb_model))
    
  }
  
  
}  

  # Adapting the number of particles ----------------------------------------
  
  if (adapt_particles) {
    if (verbose) {
      message("Adapting particles")
    }
    
    tb_model <- adapt_particles(tb_model)
  }
  
  
  # Adapting the proposal ---------------------------------------------------
  
  if (adapt_proposal) {
    if (verbose) {
      message("Adapting particles with a min acceptance of ", min_acc, " and a maximum acceptance of ", max_acc)
    }
    
    tb_model <- adapt_proposal(tb_model, min = min_acc, max = max_acc)
    
    if (verbose) {
      message("Adapted proposal distribution")
      prop_block <- get_block(tb_model$model, "proposal_parameter")
      
      print(prop_block)
    }
    
  }
  
  
  # Test model fitting ------------------------------------------------------
  
  
  if (fit) {
    if (verbose) {
      message("Fitting using PMCMC")
    }
    
    
    tb_model <- tb_model %>% 
      sample(target="posterior", obs=tb_data, sample_obs=TRUE, nsamples = 1000, verbose = libbi_verbose, nthreads = 4)
    
    
    
    # Look at chain -----------------------------------------------------------
    
    p <- plot(tb_model, plot = FALSE)
    
    if (verbose) {
      
      message("Plotting Trajectories")
      print(p$trajectories)
      
      message("Plotting traces")
      print(p$traces)
      
      message("Plotting densities")
      print(p$densities)
      
      message("Overview of all data")
      print(p$data)
    }
  }
  
  
  
  if (save_output) {
    if (verbose) {
      message("Saving model output")
    }
    
    test_data_loc <- paste0("vignettes/results/model-", Sys.Date(), "-", round(runif(1, 0, 10000)), ".rds")
    save_libbi(tb_model, test_data_loc)
    
    if (verbose) {
      message("Test data saved to: ")
      message(test_data_loc)
    }
  }
  return(tb_model)
}